"""brain.py: a small in-repo brain of one-fact notes, readable as an Obsidian vault.

    brain.py recall [TEXT...] [--phase TEXT] [--json] [--max-chars N]   the notes that match, ranked
    brain.py find TEXT... [--all]      the top 5 as `slug | status | score | title`
    brain.py new --title T --tldr S [--tags a,b] [--paths g1,g2] [--source S]
                 [--links s1,s2] [--supersedes SLUG] [--body TEXT]
    brain.py index                     regenerate INDEX.md
    brain.py init                      create the brain folder (only when the user says yes)
    brain.py pending                   print the review queue in _pending.md
    Every subcommand takes --cwd DIR.

Notes are <repo>/<brain_dir>/<slug>.md (brain_dir from config.json, default docs/brain) with a
flat `key: value` frontmatter; README.md, written by init, describes the format. With no brain
folder every subcommand is silent and exits 0. Writes only inside the brain folder. Stdlib only.
"""
import argparse
import fnmatch
import json
import os
import re
import subprocess
import sys
from datetime import date
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from yahlib import config, find_git, read_json, utf8_stdout, where_cache_path  # noqa: E402

NO_WINDOW = 0x08000000 if os.name == "nt" else 0
RESERVED = {"index.md", "_pending.md", "readme.md"}
TOP, ALSO, TLDR_MAX = 5, 10, 200
STOP = frozenset("""
    about above after again all also and any are because been before being below between both but
    could did does doing done down during each few for from further had has have having here how
    into its just more most not now off once only other our out over own same should some such than
    that the their them then there these they this those through too under until very was were what
    when where which while who why will with would you your
    can file files code make need needs want wants please get got let use using thing things like
""".split())
README = """# Project brain

Durable project facts, one per note, kept by yah (you are here). The folder opens as an Obsidian vault.

- A note is `<slug>.md`: lowercase a-z, 0-9 and dashes, 60 characters or fewer.
- Frontmatter is flat `key: value`: title, tags [a, b], paths ["glob"], status, superseded_by, source.
- The first body line is the TL;DR, 200 characters or fewer. Link other notes with [[slug]].
- `source` is evidence: a PR, commit, issue, URL, path/to/file:line, or "user, YYYY-MM-DD".
- Notes inferred without evidence wait in `_pending.md` until someone accepts or drops them.
- A fact that changed is superseded (status: superseded, superseded_by: <slug>), never deleted.
- `INDEX.md` is generated by `brain.py index`; do not edit it.
- On a session's first prompt, yah recalls only the notes that match the task and the changed files.
"""


# ---------------------------------------------------------------- notes

SHORT = frozenset("pr ui ux ci cd db qa io ai ml os js ts".split())  # 2-letter words that carry meaning


def stem(t):
    """A light stemmer, the same on both sides: pushes, pushed, pushing -> push; caches, cached -> cach."""
    if len(t) > 4 and t.endswith("ies"):
        return t[:-3] + "y"
    if t.endswith(("ches", "shes", "xes", "zes")) and len(t) > 4 or t.endswith("sses"):
        t = t[:-2]
    elif len(t) > 5 and t.endswith(("ing", "ed")):
        t = t[:-3] if t.endswith("ing") else t[:-2]
    elif len(t) > 3 and t.endswith("s") and not t.endswith(("ss", "us", "is")):
        t = t[:-1]
    return t[:-1] if len(t) > 4 and t.endswith("e") else t


def tokens(text):
    out = set()
    for t in re.split(r"[^a-z0-9]+", (text or "").lower()):
        if (len(t) < 3 and t not in SHORT) or t in STOP:
            continue
        out.add(stem(t))
    return out


def one_line(text):
    return " ".join(str(text or "").split())


def clip(text, n):
    text = one_line(text)
    return text if len(text) <= n else text[:n - 3] + "..."


def csv(text):
    return [v.strip() for v in (text or "").split(",") if v.strip()]


def unquote(v):
    v = v.strip()
    return v[1:-1] if len(v) >= 2 and v[0] == v[-1] and v[0] in "\"'" else v


def split_front(text):
    """(frontmatter lines, body lines); ([], all lines) when there is no frontmatter."""
    lines = text.splitlines()
    if lines and lines[0].strip() == "---":
        for i in range(1, len(lines)):
            if lines[i].strip() == "---":
                return lines[1:i], lines[i + 1:]
    return [], lines


def parse_front(lines):
    """The strict subset: `key: value` per line, lists as [a, b] or ["a", "b"]."""
    meta = {}
    for ln in lines:
        key, sep, val = ln.partition(":")
        key, val = key.strip().lower(), val.strip()
        if not sep or not key:
            continue
        if val.startswith("[") and val.endswith("]"):
            meta[key] = [unquote(v) for v in val[1:-1].split(",") if unquote(v)]
        else:
            meta[key] = unquote(val)
    return meta


def as_list(v):
    return v if isinstance(v, list) else [v] if v else []


def scalar(v):
    return ", ".join(v) if isinstance(v, list) else str(v or "")


def read_note(path):
    front, body = split_front(path.read_text(encoding="utf-8-sig", errors="replace"))
    m = parse_front(front)
    title, tags = scalar(m.get("title")) or path.stem, as_list(m.get("tags"))
    tldr = next((ln.strip() for ln in body if ln.strip()), "")[:TLDR_MAX]
    links = {ln.strip() for ln in re.findall(r"\[\[([^\]|#]+)", "\n".join(body))}
    return {"slug": path.stem, "title": title, "tags": tags, "paths": as_list(m.get("paths")),
            "status": "superseded" if scalar(m.get("status")).lower() == "superseded" else "active",
            "superseded_by": scalar(m.get("superseded_by")), "source": scalar(m.get("source")),
            "tldr": tldr, "links": sorted(ln for ln in links if ln),
            "words": (tokens(title), tokens(" ".join(tags)), tokens(tldr))}


def load_notes(bdir):
    notes = []
    for f in sorted(bdir.glob("*.md")):
        if f.name.lower() in RESERVED or not f.is_file():
            continue
        try:
            notes.append(read_note(f))
        except Exception:
            pass
    return notes


def write(path, text):
    """UTF-8 with \\n line ends on every OS, so generated files are byte-identical."""
    path.write_bytes(text.encode("utf-8"))


def locate(cwd):
    """(repo toplevel, brain folder), or (None, None) outside a git repo. The folder may not exist."""
    top = find_git(cwd or os.getcwd())[0]
    return (None, None) if top is None else (Path(top), Path(top) / config()["brain_dir"])


def brain_dir(cwd):
    """The brain folder when it exists, else None."""
    bdir = locate(cwd)[1]
    return bdir if bdir is not None and bdir.is_dir() else None


def rel_dir():
    return config()["brain_dir"].replace("\\", "/")


def pending_entries(bdir):
    try:
        return (bdir / "_pending.md").read_text(encoding="utf-8-sig", errors="replace").strip()
    except OSError:
        return ""


def pending_count(bdir):
    return sum(1 for ln in pending_entries(bdir).splitlines() if ln.startswith("## "))


# ---------------------------------------------------------------- changed files

def git(top, *args):
    try:
        p = subprocess.run(["git", "-c", "core.quotePath=off", *args], cwd=str(top), capture_output=True,
                           stdin=subprocess.DEVNULL, timeout=3, creationflags=NO_WINDOW)
        return p.stdout.decode("utf-8", "replace") if p.returncode == 0 else None
    except Exception:
        return None


def changed_files(top, base=""):
    """`git diff --name-only <base>...HEAD` plus `git status` paths, minus the brain folder's own files
    (its README.md would suffix-match every `paths: [README.md]` note). A repo with no commits yet
    gives no path signal: every file is new there. A failed call adds nothing."""
    status = (git(top, "status", "--porcelain=v1", "-b", "--untracked-files=all") or "").splitlines()
    if status and status[0].startswith(("## No commits yet on ", "## Initial commit on ")):
        return set()
    out = set()
    for ref in [r for r in (base, "origin/HEAD", "main", "master") if r]:
        txt = git(top, "diff", "--name-only", ref + "...HEAD")
        if txt is not None:
            out.update(ln.strip() for ln in txt.splitlines() if ln.strip())
            break
    for ln in status:
        path = "" if ln.startswith("## ") else ln[3:].split(" -> ")[-1].strip().strip('"')
        if path:
            out.add(path)
    skip = rel_dir()
    skip = os.path.normcase((skip[2:] if skip.startswith("./") else skip) + "/")
    return {p for p in out if not os.path.normcase(p).startswith(skip)}  # normcase: Docs/Brain == docs/brain on Windows


_GLOBS = {}


def glob_hit(glob, paths):
    """fnmatch with `**` for any depth (zero included), against the full path or any path suffix."""
    g = glob.strip().replace("\\", "/").lstrip("/")
    g = g[2:] if g.startswith("./") else g
    if g not in _GLOBS:
        _GLOBS[g] = [re.compile(r"(?s:.*/)?" + fnmatch.translate(v)) for v in {g, g.replace("**/", "")} if v]
    return any(rx.match(p) for rx in _GLOBS[g] for p in paths)


def cache_phase(cwd):
    """The where cache's current phase for this repo, {} when there is none."""
    main_root = find_git(cwd or os.getcwd())[1]
    cache = read_json(where_cache_path(main_root), {}) if main_root else {}
    phase = cache.get("phase") if isinstance(cache, dict) else None
    return phase if isinstance(phase, dict) else {}


# ---------------------------------------------------------------- ranking

def rank(notes, text, phase="", changed=()):
    """[(score, note)] for the notes scoring above 0, best first."""
    q, ph = tokens(text), tokens(phase)
    score = {}
    for n in notes:
        title, tags, tldr = n["words"]
        s = 3 * len(q & title) + 2 * len(q & tags) + len(q & tldr) + 1.5 * len(ph & (title | tags))
        if changed and any(glob_hit(g, changed) for g in n["paths"]):
            s += 4 if s else 2  # a changed file alone ranks below any word match
        score[n["slug"]] = s

    def order(n):
        return -score[n["slug"]], n["title"].lower(), n["slug"]

    hits = sorted((n for n in notes if score[n["slug"]] > 0), key=order)
    top = {n["slug"] for n in hits[:TOP]}
    near = {ln for n in hits[:TOP] for ln in n["links"] if ln != n["slug"]}
    near |= {n["slug"] for n in notes if any(ln in top and ln != n["slug"] for ln in n["links"])}
    for slug in near:
        if score.get(slug, 0) > 0:
            score[slug] += 1
    return [(score[n["slug"]], n) for n in sorted(hits, key=order)]


def recall(cwd, text="", phase=None):
    """The ranked recall for the repo at cwd, or None when it has no brain folder.
    phase=None takes the phase title and NEXT from the where cache."""
    top, bdir = locate(cwd)
    if bdir is None or not bdir.is_dir():
        return None
    notes = [n for n in load_notes(bdir) if n["status"] == "active"]
    cur = cache_phase(cwd)
    if phase is None:
        phase = " ".join(str(cur.get(k) or "") for k in ("title", "next"))
    changed = changed_files(top, str(cur.get("base") or "")) if any(n["paths"] for n in notes) else set()
    hits = rank(notes, text, phase, changed)
    return {"brain_dir": rel_dir(), "total": len(notes), "count": len(hits),
            "query": clip(text if text.strip() else phase, 60),
            "matches": [{"slug": n["slug"], "title": n["title"], "tldr": n["tldr"], "source": n["source"],
                         "score": round(s, 2)} for s, n in hits[:TOP]],
            "also": [n["slug"] for _, n in hits[TOP:TOP + ALSO]], "pending": pending_count(bdir)}


def render(r, max_chars):
    """The recall block within max_chars: trim the also list first, then TL;DRs from the bottom."""
    if not r or not r["matches"]:
        return ""
    head = '[yah] brain: {} of {} notes match "{}" ({}, full list in INDEX.md)'.format(
        r["count"], r["total"], r["query"], r["brain_dir"])
    n = r["pending"]
    tail = ["{} unreviewed note{} in {}/_pending.md".format(n, "" if n == 1 else "s", r["brain_dir"])] if n else []
    also, full = list(r["also"]), [True] * len(r["matches"])

    def build():
        lines = [head]
        for m, keep in zip(r["matches"], full):
            src = " ({})".format(m["source"]) if m["source"] else ""
            lines.append("- {}: {}{}".format(m["slug"], m["tldr"], src) if keep and m["tldr"] else "- " + m["slug"])
        if also:
            lines.append("Also related: " + ", ".join(also))
        return lines + tail

    lines = build()
    while len("\n".join(lines)) > max_chars and also:
        also.pop()
        lines = build()
    for i in reversed(range(len(full))):
        if len("\n".join(lines)) <= max_chars:
            break
        full[i] = False
        lines = build()
    while len("\n".join(lines)) > max_chars and len(lines) > 1:
        lines.pop()
    return "\n".join(lines)[:max_chars]


# ---------------------------------------------------------------- writing

def build_index(notes):
    """(INDEX.md text, warnings). Deterministic: sorted by slug, no timestamps."""
    notes = sorted(notes, key=lambda n: n["slug"])
    slugs = {n["slug"] for n in notes}
    active = [n for n in notes if n["status"] == "active"]
    old = [n for n in notes if n["status"] != "active"]
    warn = []
    for n in notes:
        if not n["source"]:
            warn.append("{}: no source".format(n["slug"]))
        warn += ["{}: broken link [[{}]]".format(n["slug"], ln) for ln in n["links"] if ln not in slugs]
        if n["status"] != "active" and n["superseded_by"] not in slugs:
            warn.append("{}: superseded_by '{}' points nowhere".format(n["slug"], n["superseded_by"]))

    def entry(n):
        tldr = ": " + n["tldr"] if n["tldr"] else ""
        return "- [[{}]] {}{}{}".format(n["slug"], n["title"], tldr, " ({})".format(n["source"]) if n["source"] else "")

    lines = ["# Brain index", "",
             "Generated by brain.py index; do not edit. {} active, {} superseded. Unreviewed notes wait in "
             "_pending.md.".format(len(active), len(old)), ""]
    lines += [entry(n) for n in active] or ["(no notes yet)"]
    if old:
        lines += ["", "## Superseded"]
        lines += ["- [[{}]] {} (superseded by [[{}]])".format(n["slug"], n["title"], n["superseded_by"]) for n in old]
    return "\n".join(lines) + "\n", warn


def write_index(bdir):
    """Regenerate INDEX.md (only when it changed); warnings go to stderr. Returns the note count."""
    notes = load_notes(bdir)
    text, warn = build_index(notes)
    path = bdir / "INDEX.md"
    if not path.is_file() or path.read_bytes() != text.encode("utf-8"):
        write(path, text)
    for w in warn:
        print("[yah] brain: " + w, file=sys.stderr)
    return len(notes)


def set_front(path, updates):
    """Set frontmatter keys in place, keeping every other line."""
    front, body = split_front(path.read_text(encoding="utf-8-sig", errors="replace"))
    out, seen = [], set()
    for ln in front:
        key = ln.partition(":")[0].strip().lower()
        if key in updates:
            if key not in seen:
                out.append("{}: {}".format(key, updates[key]))
                seen.add(key)
            continue
        out.append(ln)
    out += ["{}: {}".format(k, v) for k, v in updates.items() if k not in seen]
    write(path, "\n".join(["---"] + out + ["---"] + body) + "\n")


def slugify(title):
    s = re.sub(r"[^a-z0-9]+", "-", title.lower()).strip("-")[:60].rstrip("-") or "note"
    return s + "-note" if s + ".md" in RESERVED else s


def note_text(title, tldr, tags, paths, source, links, body):
    lines = ["---", "title: " + title]
    if tags:
        lines.append("tags: [{}]".format(", ".join(tags)))
    if paths:
        lines.append("paths: [{}]".format(", ".join('"{}"'.format(p) for p in paths)))
    lines += ["status: active", "source: " + source, "---", tldr]
    if body:
        lines.append(body)
    if links:
        lines.append("Links: {}.".format(", ".join("[[{}]]".format(ln) for ln in links)))
    return "\n".join(lines) + "\n"


def add_pending(bdir, a, title, tldr):
    entry = ["## {} {}".format(date.today().isoformat(), title), "- tldr: " + tldr]
    for label, vals in (("tags", csv(a.tags)), ("paths", csv(a.paths)), ("links", csv(a.links))):
        if vals:
            entry.append("- {}: {}".format(label, ", ".join(vals)))
    if a.supersedes:
        entry.append("- supersedes: " + a.supersedes.strip())
    if one_line(a.body):
        entry.append("- detail: " + one_line(a.body))
    entry.append("- why pending: no source. Accept it with `brain.py new ... --source <evidence>`, or drop it.")
    old = pending_entries(bdir)
    write(bdir / "_pending.md", (old + "\n\n" if old else "") + "\n".join(entry) + "\n")
    write_index(bdir)
    print("pending: {} -> {}/_pending.md (no source, so it waits for review)".format(title, rel_dir()))
    return 0


# ---------------------------------------------------------------- commands

def cmd_recall(a):
    r = recall(a.cwd, " ".join(a.text), a.phase)
    if r is None:
        return 0
    if a.json:
        print(json.dumps({k: r[k] for k in ("brain_dir", "total", "matches", "also", "pending")},
                         ensure_ascii=False))
        return 0
    block = render(r, a.max_chars or int(config()["recall_max_chars"]))
    if block:
        print(block)
    return 0


def cmd_find(a):
    bdir = brain_dir(a.cwd)
    if bdir is None:
        return 0
    notes = [n for n in load_notes(bdir) if a.all or n["status"] == "active"]
    hits = rank(notes, " ".join(a.text))[:TOP]
    for s, n in hits:
        print("{} | {} | {:g} | {}".format(n["slug"], n["status"], s, n["title"]))
    if not hits:
        print("no matching notes")
    return 0


def cmd_new(a):
    bdir = brain_dir(a.cwd)
    if bdir is None:
        print("[yah] brain: no brain folder here; /yah:start offers to create one", file=sys.stderr)
        return 0
    title, tldr, source = one_line(a.title), one_line(a.tldr), one_line(a.source)
    if not title or not tldr or len(tldr) > TLDR_MAX:
        print("[yah] brain: --title and --tldr are required; the tldr holds {} characters or fewer "
              "(this one has {})".format(TLDR_MAX, len(tldr)), file=sys.stderr)
        return 1
    if not source:
        return add_pending(bdir, a, title, tldr)
    slug = slugify(title)
    path = bdir / (slug + ".md")
    if path.exists():
        print("exists: {}; update it or pass --supersedes".format(slug), file=sys.stderr)
        return 1
    old = None
    if a.supersedes:
        stem = re.sub(r"\.md$", "", a.supersedes.strip())
        old = bdir / (stem + ".md")
        if not re.fullmatch(r"[a-z0-9-]{1,64}", stem) or old.name in RESERVED or not old.is_file():
            print("[yah] brain: no note to supersede: " + a.supersedes, file=sys.stderr)
            return 1
    body = "\n".join(ln.rstrip() for ln in (a.body or "").strip().splitlines())
    write(path, note_text(title, tldr, csv(a.tags), csv(a.paths), source, csv(a.links), body))
    print("wrote {}/{}.md".format(rel_dir(), slug))
    if old is not None:
        set_front(old, {"status": "superseded", "superseded_by": slug})
        print("superseded {} -> {}".format(old.stem, slug))
    write_index(bdir)
    return 0


def cmd_index(a):
    bdir = brain_dir(a.cwd)
    if bdir is not None:
        print("wrote {}/INDEX.md ({} notes)".format(rel_dir(), write_index(bdir)))
    return 0


def cmd_init(a):
    top, bdir = locate(a.cwd)
    if top is None:
        print("[yah] brain: not in a git repo; nothing created", file=sys.stderr)
        return 0
    existed = bdir.is_dir()
    bdir.mkdir(parents=True, exist_ok=True)
    if not (bdir / "README.md").exists():
        write(bdir / "README.md", README)
    if not (bdir / "_pending.md").exists():
        write(bdir / "_pending.md", "")
    write_index(bdir)
    print("{} already exists; INDEX.md is up to date".format(rel_dir()) if existed else
          "created {} with README.md, _pending.md and INDEX.md".format(rel_dir()))
    return 0


def cmd_pending(a):
    bdir = brain_dir(a.cwd)
    if bdir is None:
        return 0
    text, n = pending_entries(bdir), pending_count(bdir)
    if not text:
        print("no pending notes in {}/_pending.md".format(rel_dir()))
        return 0
    print("{} pending in {}/_pending.md. Accept one: `brain.py new ... --source <evidence>`, then delete its "
          "entry. Drop one: delete its entry.\n\n{}".format(n, rel_dir(), text))
    return 0


def main():
    utf8_stdout()
    ap = argparse.ArgumentParser(prog="brain.py", description="The project brain: one durable fact per note.")
    common = argparse.ArgumentParser(add_help=False)
    common.add_argument("--cwd", help="run as if started in this directory")
    sub = ap.add_subparsers(dest="cmd")
    p = sub.add_parser("recall", parents=[common], help="print the notes that match TEXT and the phase")
    p.add_argument("text", nargs="*")
    p.add_argument("--phase", help="phase text (default: the where cache's phase title and NEXT)")
    p.add_argument("--json", action="store_true")
    p.add_argument("--max-chars", type=int)
    p = sub.add_parser("find", parents=[common], help="the top 5 notes for TEXT")
    p.add_argument("text", nargs="+")
    p.add_argument("--all", action="store_true", help="include superseded notes")
    p = sub.add_parser("new", parents=[common], help="write a note, or queue it in _pending.md without --source")
    p.add_argument("--title", required=True)
    p.add_argument("--tldr", required=True)
    for flag in ("--tags", "--paths", "--source", "--links", "--supersedes", "--body"):
        p.add_argument(flag, default="")
    sub.add_parser("index", parents=[common], help="regenerate INDEX.md")
    sub.add_parser("init", parents=[common], help="create the brain folder")
    sub.add_parser("pending", parents=[common], help="print the entries waiting for review")
    a = ap.parse_args()
    commands = {"recall": cmd_recall, "find": cmd_find, "new": cmd_new, "index": cmd_index,
                "init": cmd_init, "pending": cmd_pending}
    if a.cmd not in commands:
        ap.print_help()
        return 0
    return commands[a.cmd](a)


if __name__ == "__main__":
    try:
        code = main()
    except Exception as e:  # never break a session or a skill
        print("[yah] brain.py failed: {}".format(e), file=sys.stderr)
        code = 0
    sys.exit(code)
